export const LOAD_AND_FETCH = "LOAD_AND_FETCH";
export const LOAD_AND_FETCH_SINGLE_PRODUCT = "LOAD_AND_FETCH_SINGLE_PRODUCT";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const SET_QUANTITY = "SET_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const TOTAL_AMOUNT = "TOTAL_AMOUNT";
